import { Post } from '@/types';

export const INITIAL_POSTS: Post[] = [
  {
    id: 1,
    nombre: 'Calculadora Científica Casio FX-991LAX Classwiz',
    desc: 'En perfecto estado, incluye estuche protector y manual de usuario. Excelente para cálculo diferencial, física y álgebra lineal.',
    price: '120000',
    sede: 'Sede Piedra de Bolívar',
    tipoP: 'Calculadoras y Tecnología',
    userId: 101,
    user: {
      id: 101,
      title: 'Carlos M.',
      name: 'Carlos Mendoza',
      mail: 'cmendoza@unicartagena.edu.co',
      codEst: '0222010045',
      sede: 'Sede Piedra de Bolívar',
      role: 'Estudiante',
      cellphone: '3004567890',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [
      {
        id: 1,
        valoration: 'Excelente vendedor, me entregó la calculadora en la biblioteca de Piedra sin demora.',
        postId: 1,
        userId: 102,
      },
    ],
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 2,
    nombre: 'Bata de Laboratorio Antifluido Manga Larga (Talla M)',
    desc: 'Bata clínica unisex antifluido con puños elásticos y botones reforzados. Prácticamente nueva, usada solo en dos rotaciones de laboratorio.',
    price: '45000',
    sede: 'Sede Zaragocilla',
    tipoP: 'Uniformes y Batas',
    userId: 102,
    user: {
      id: 102,
      title: 'Valeria R.',
      name: 'Valeria Ramos',
      mail: 'vramos@unicartagena.edu.co',
      codEst: '0121020088',
      sede: 'Sede Zaragocilla',
      role: 'Estudiante',
      cellphone: '3109876543',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 3,
    nombre: 'Atlas de Anatomía Humana - Frank Netter (7ma Edición)',
    desc: 'Tapa dura original a todo color con ilustraciones completas. Sin tachones, perfecto para materias de morfología y anatomía clínica.',
    price: '180000',
    sede: 'Sede Zaragocilla',
    tipoP: 'Libros y Fotocopias',
    userId: 103,
    user: {
      id: 103,
      title: 'Andrés G.',
      name: 'Andrés Gómez',
      mail: 'agomez@unicartagena.edu.co',
      codEst: '0120010012',
      sede: 'Sede Zaragocilla',
      role: 'Estudiante',
      cellphone: '3157891234',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 4,
    nombre: 'Código Civil y Código de Comercio (Legis 2024)',
    desc: 'Edición con anotaciones jurisprudenciales y concordancias actualizadas. Entrega directa en los pasillos o biblioteca de San Agustín.',
    price: '65000',
    sede: 'Claustro San Agustín',
    tipoP: 'Libros y Fotocopias',
    userId: 104,
    user: {
      id: 104,
      title: 'Mariana P.',
      name: 'Mariana Palacio',
      mail: 'mpalacio@unicartagena.edu.co',
      codEst: '0321010023',
      sede: 'Claustro San Agustín',
      role: 'Estudiante',
      cellphone: '3012345678',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
  },
  {
    id: 5,
    nombre: 'Fonendoscopio Littmann Classic III Negro Mate',
    desc: 'Original 3M en caja con olivas blandas de repuesto. Campana de doble cara, diafragma sintonizable y excelente respuesta acústica.',
    price: '290000',
    sede: 'Sede Zaragocilla',
    tipoP: 'Instrumentos y Salud',
    userId: 105,
    user: {
      id: 105,
      title: 'Diego H.',
      name: 'Diego Herrera',
      mail: 'dherrera@unicartagena.edu.co',
      codEst: '0119020056',
      sede: 'Sede Zaragocilla',
      role: 'Estudiante',
      cellphone: '3206549871',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: 6,
    nombre: 'Principios de Economía - N. Gregory Mankiw (8va Ed.)',
    desc: 'Texto guía indispensable para micro y macroeconomía. Forrado en papel contact transparente, tablas y gráficos limpios.',
    price: '85000',
    sede: 'Sede San Pablo',
    tipoP: 'Libros y Fotocopias',
    userId: 106,
    user: {
      id: 106,
      title: 'Laura S.',
      name: 'Laura Salcedo',
      mail: 'lsalcedo@unicartagena.edu.co',
      codEst: '0421010034',
      sede: 'Sede San Pablo',
      role: 'Estudiante',
      cellphone: '3128765432',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 60).toISOString(),
  },
  {
    id: 7,
    nombre: 'Juego de Escuadras Técnicas 30cm y Escalímetro Profesional',
    desc: 'Escuadras biseladas Faber-Castell y escalímetro de aluminio de 6 escalas. Usado en dibujo técnico de Ingeniería Civil.',
    price: '35000',
    sede: 'Sede Piedra de Bolívar',
    tipoP: 'Otros',
    userId: 107,
    user: {
      id: 107,
      title: 'Jorge T.',
      name: 'Jorge Torres',
      mail: 'jtorres@unicartagena.edu.co',
      codEst: '0221020067',
      sede: 'Sede Piedra de Bolívar',
      role: 'Estudiante',
      cellphone: '3029871234',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: 8,
    nombre: 'Calculadora Financiera HP 12C Platinum',
    desc: 'Edición Platinum con memoria extendida y cálculo en modo RPN o algebraico. Baterías recién cambiadas y funda de cuero original.',
    price: '140000',
    sede: 'Sede San Pablo',
    tipoP: 'Calculadoras y Tecnología',
    userId: 108,
    user: {
      id: 108,
      title: 'Camila V.',
      name: 'Camila Vega',
      mail: 'cvega@unicartagena.edu.co',
      codEst: '0420020019',
      sede: 'Sede San Pablo',
      role: 'Estudiante',
      cellphone: '3187654321',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1611095973763-414019e72400?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 3600000 * 84).toISOString(),
  },
];
