import { Post } from '@/types';

export const INITIAL_POSTS: Post[] = [
  {
    id: 1,
    nombre: 'Calculadora Científica Texas Instruments TI-Nspire CX II',
    desc: 'Excelente estado, ideal para cálculo, álgebra lineal y física en Ingeniería de Sistemas o Civil. Incluye cable de carga y estuche protector original.',
    price: '280000',
    sede: 'Piedra de Bolívar',
    tipoP: 'Calculadoras y Tecnología',
    userId: 2,
    user: {
      id: 2,
      title: 'Carlos Mendoza',
      mail: 'cmendoza@unicartagena.edu.co',
      codEst: '0221910045',
      sede: 'Piedra de Bolívar',
      role: 'Estudiante',
      cellphone: '3015489210',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [
      {
        id: 101,
        valoration: 'Excelente vendedor, el producto está como nuevo. Recomendado 100%.',
        postId: 1,
        userId: 3,
        user: {
          id: 3,
          title: 'Andrea Gómez',
          mail: 'agomez@unicartagena.edu.co',
          codEst: '0222010012',
          sede: 'Piedra de Bolívar',
          role: 'Estudiante',
          cellphone: '3104567890',
        },
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 2,
    nombre: 'Bata de Laboratorio Antifluido Talla M (Medicina / Odontología)',
    desc: 'Bata blanca antifluido con el logo bordado de la Universidad de Cartagena. Apenas un semestre de uso, sin manchas ni roturas.',
    price: '45000',
    sede: 'Zaragocilla',
    tipoP: 'Uniformes y Batas',
    userId: 4,
    user: {
      id: 4,
      title: 'Valentina Rios',
      mail: 'vrios@unicartagena.edu.co',
      codEst: '0221820033',
      sede: 'Zaragocilla',
      role: 'Estudiante',
      cellphone: '3157891234',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [
      {
        id: 102,
        valoration: 'Muy buena tela y la talla corresponde exacto.',
        postId: 2,
        userId: 2,
        user: {
          id: 2,
          title: 'Carlos Mendoza',
          mail: 'cmendoza@unicartagena.edu.co',
          codEst: '0221910045',
          sede: 'Piedra de Bolívar',
          role: 'Estudiante',
          cellphone: '3015489210',
        },
        created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 3,
    nombre: 'Libro Stewart Cálculo Trascendentes Tempranas 8va Edición',
    desc: 'Texto guía obligatorio para Cálculo I, II y Multivariable. Pasta dura, incluye formularios y ejercicios resueltos al final.',
    price: '70000',
    sede: 'Piedra de Bolívar',
    tipoP: 'Libros y Fotocopias',
    userId: 5,
    user: {
      id: 5,
      title: 'Mateo Herrera',
      mail: 'mherrera@unicartagena.edu.co',
      codEst: '0222110089',
      sede: 'Piedra de Bolívar',
      role: 'Estudiante',
      cellphone: '3008901234',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 4,
    nombre: 'Habitación Amoblada cerca a Zaragocilla (Incluye Servicios + WiFi)',
    desc: 'Habitación para estudiante universitario a 3 cuadras del campus de la salud. Incluye cama, closet, ventilador, baño compartido, agua, luz e internet de alta velocidad.',
    price: '420000',
    sede: 'Zaragocilla',
    tipoP: 'Habitaciones y Alquiler',
    userId: 6,
    user: {
      id: 6,
      title: 'Doña Martha (Arrendataria)',
      mail: 'marthap@gmail.com',
      codEst: 'EXT-004',
      sede: 'Zaragocilla',
      role: 'Administrativo',
      cellphone: '3126789012',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [
      {
        id: 103,
        valoration: 'Ambiente muy tranquilo y seguro para estudiar.',
        postId: 4,
        userId: 4,
        user: {
          id: 4,
          title: 'Valentina Rios',
          mail: 'vrios@unicartagena.edu.co',
          codEst: '0221820033',
          sede: 'Zaragocilla',
          role: 'Estudiante',
          cellphone: '3157891234',
        },
        created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 5,
    nombre: 'Tutorías de Programación en Go, Python y Estructuras de Datos',
    desc: 'Estudiante de 9no semestre de Ingeniería de Sistemas ofrece asesorías personalizadas para proyectos, parciales y talleres de algoritmos.',
    price: '25000',
    sede: 'San Agustín',
    tipoP: 'Servicios y Tutorías',
    userId: 7,
    user: {
      id: 7,
      title: 'Javier Cuesta',
      mail: 'jcuesta@unicartagena.edu.co',
      codEst: '0221710001',
      sede: 'San Agustín',
      role: 'Estudiante',
      cellphone: '3045678901',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [
      {
        id: 104,
        valoration: 'Me explicó súper bien para el parcial de estructuras. Pasé con 4.5!',
        postId: 5,
        userId: 5,
        user: {
          id: 5,
          title: 'Mateo Herrera',
          mail: 'mherrera@unicartagena.edu.co',
          codEst: '0222110089',
          sede: 'Piedra de Bolívar',
          role: 'Estudiante',
          cellphone: '3008901234',
        },
        created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 6,
    nombre: 'Kit de Disección Quirúrgica en Acero Inoxidable (14 Piezas)',
    desc: 'Estuche de cuero con pinzas Kelly, tijeras Mayo, mangos de bisturí #3 y #4, sonda acanalada y separadores. Aprobado para anatomía y cirugía.',
    price: '65000',
    sede: 'Zaragocilla',
    tipoP: 'Instrumentos y Salud',
    userId: 8,
    user: {
      id: 8,
      title: 'Laura Barrios',
      mail: 'lbarrios@unicartagena.edu.co',
      codEst: '0221920055',
      sede: 'Zaragocilla',
      role: 'Estudiante',
      cellphone: '3189012345',
    },
    imagenes: [
      'https://images.unsplash.com/photo-1583912267670-6575ad4736f8?w=800&auto=format&fit=crop&q=80',
    ],
    valorations: [],
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];
